### ISSUE TITLE
display the input text file into the input box

### ISSUE THREAD

**Issue by mlmabuti** [mlmabuti/tokens-please#2]
use state hooks to display the user input text into the inputbox under Input ✋ section

**Comment by adrianmarinwork** [comment]
Hello ss you can see I have created a pull request with the task done.
But I have a question related to this issue, how is it that you wanted to do it DOM manipulation? I'm pretty new with the React framework but why wouldn't you like it to be done with reactive variables that you pass to the child component and updates when the user adds a file and you read the content of it?.
Thank you!

**Comment by mlmabuti** [comment]
Hi! sorry I meant to change that to use state hooks, I got used the vanilla js way of handling dom changes. I'm also new to react as well, this is my first project. Thanks for bringing this up!
